In [1]:
# INDEXING AND SLICING 

In [4]:
import numpy as np 
var1 = np.array([[4,5,6],[7,8,9]])
print(var1)
print(var1[1,0])
print(var1[1,2])

[[4 5 6]
 [7 8 9]]
7
9


In [8]:
var2 = np.array([[[1,2],[3,4],[5,6]],
                [[7,8],[8,9],[9,10]]])
print(var2)
print(var2[0,2,1])
print(var2[1,1,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 8  9]
  [ 9 10]]]
6
8


In [23]:
# SLICING PARAMETERS 
# ARRAY[ START : STOP : STEP]
var3 = np.array([1,2,3,4,5,6,7])
print(var3[0:6])
print(var3[0:-1])
print(var3[2:7:2])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[3 5 7]


In [28]:
# FOR 2-D ARRAYS 
var4 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,0]])
print(var4)
print(var4[0,1:2])
print(var4[2,1:3])
print(var4[1,0:4])

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]
[2]
[8 9]
[4 5 6 7]


In [30]:
# NITERATOR 
var5 = np.array([[[1,2,3,4,5],[5,6,7,8,9]]])
print(var5)
print(var5.ndim)
for i in np.nditer(var5):
    print(i)

[[[1 2 3 4 5]
  [5 6 7 8 9]]]
3
1
2
3
4
5
5
6
7
8
9


In [31]:
var6 = np.array([[[1,2,3,4,5],[5,6,7,8,9]]])
print(var6)
print(var6.ndim)
for i,d in np.ndenumerate(var6):
    print(i,d)

[[[1 2 3 4 5]
  [5 6 7 8 9]]]
3
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 1, 4) 9


In [37]:
var7 = np.array([1,2,3,4,5])
var8 = var7.copy() # COPY DOES NOT CHANGE ORGIGINAL DATA . IT OWNS THE DATA 
print(var8)
var7[2] = 8
var8 = var7.copy()
var9 = var7.view() # VIEW CHANGES ORIGINAL DATA . IT DOES OWNS THE DATA 
print(var9)

[1 2 3 4 5]
[1 2 8 4 5]
